animes = ['nazo no kanojo']
moreAnimes= ["Call of the night","Dr. Stone","Re-zero"]

print(animes)
print("Append")
animes.append('jojos')  
animes.append('city animation')
animes.append("Re-zero")
print(animes)
print("Insert")
animes.insert(2,"Stain-Gate")
print(animes)
print("Remove")
animes.remove("Re-zero")
print(animes)
print("Index")
print(animes.index("jojos"))
print("Count")
print(animes.count("Re-zero"))
print("Sort")
animes.sort()
print(animes)
print("Copy")
Copy=animes.copy()
print(Copy)
print("Extend")
animes.extend(moreAnimes)
print(animes)
print("Pop last")
animes.pop(-1)
print(animes)
print("Pop First")
animes.pop(0)
print(animes)
print("Reverse")
animes.sort(reverse=True)
print(animes)
print("Map")
animes=list(map(lambda x:x.upper(),animes))
print(animes)
print("Filter")
animes=list(filter(lambda y:  len(y) <= 9, animes))
print(animes)
print("Clear")
animes.clear()
print(animes)


